DROP TABLE IF EXISTS categories;

CREATE TABLE IF NOT EXISTS categories
(
	id INT  AUTO_INCREMENT PRIMARY KEY,
	parent_id INT,
	name VARCHAR(255) NOT NULL,
	code VARCHAR(3) 
);

DROP TABLE IF EXISTS reading;

CREATE TABLE IF NOT EXISTS reading
(
	id INT AUTO_INCREMENT PRIMARY KEY,
	start DATETIME NOT NULL,
	end DATETIME NOT NULL
);

DROP TABLE IF EXISTS totals;

CREATE TABLE IF NOT EXISTS totals
(
	id INT AUTO_INCREMENT PRIMARY KEY,
	category_id INT NOT NULL,
	qty INT DEFAULT 0,
	ammount DECIMAL(12,2) DEFAULT 00,
	currency CHAR(3) NOT NULL,
	reading_id INT NOT NULL
);


 